[package]
name = "olympic_medals"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1.1"
regex = "1.10.5"
scraper = "0.19"
num-format = "0.4"
chrono = "*"
